# To get started with Dependabot version updates, youâ€™ll need to specify which package ecosystems to update and where the package manifests are located.
# Configuration options: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
<<<<<<< HEAD
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
=======
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
>>>>>>> 6f79ca229b85661d02da810c654eb8f474b1494c
